version: "3.9"
services:
  dev:
    build: .
    volumes:
      - .:/app
    ports:
      - "5173:5173"   # frontend
      - "8787:8787"   # backend
    working_dir: /app
    command: bash -c "turbo run dev --parallel"
